import React, { createContext, useContext, useState, useEffect } from "react";

const ThemeContext = createContext();

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error("useTheme must be used within ThemeProvider");
  }
  return context;
};

export const ThemeProvider = ({ children }) => {
  const [theme, setTheme] = useState(() => {
    return localStorage.getItem("posterizarr-theme") || "dark";
  });

  // Define your themes and the CSS variables they control
  const themes = {
    dark: {
      name: "Dark",
      variables: {
        "--theme-primary": "rgb(170, 170, 170)",
        "--theme-primary-hover": "rgba(255, 255, 255, 0.45)",
        "--theme-accent": "#7a7a7a",
        "--theme-bg": "#141414",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#2d2d2d",
        "--theme-bg-hover": "#3a3a3a",
        "--theme-border": "#3a3a3a",
        "--theme-text": "#ddd",
        "--theme-text-muted": "#999",
        "--theme-text-hover": "#fff",
        "--button-color": "#7a7a7a",
        "--button-color-hover": "#9b9b9b",
        "--button-text": "#eee",
        "--button-text-hover": "#fff",
        "--link-color": "#7a7a7a",
        "--link-color-hover": "#fff",
        "--label-text-color": "#000000",
        "--modal-bg-color":
          "linear-gradient(135deg, #3a3a3a, #2d2d2d, #202020, #141414, #000000)",
        "--modal-header-color":
          "linear-gradient(135deg, #3a3a3a, #2d2d2d, #202020, #141414, #000000)",
        "--modal-footer-color":
          "linear-gradient(135deg, #3a3a3a, #2d2d2d, #202020, #141414, #000000)",
        "--drop-down-menu-bg": "#2d2d2d",
        "--accent-color": "170, 170, 170",
        "--accent-color-hover": "rgba(255, 255, 255, 0.45)",
        "--arr-queue-color": "#6b5",
        "--plex-poster-unwatched": "#e5a00d",
      },
    },
    plex: {
      name: "Plex",
      variables: {
        "--theme-primary": "#e5a00d",
        "--theme-primary-hover": "#cc8f0c",
        "--theme-accent": "#282a2d",
        "--theme-bg":
          "radial-gradient(circle farthest-side at 0% 100%, rgb(47, 47, 47) 0%, rgba(47, 47, 47, 0) 100%), radial-gradient(circle farthest-side at 100% 100%, rgb(63, 63, 63) 0%, rgba(63, 63, 63, 0) 100%), radial-gradient(circle farthest-side at 100% 0%, rgb(76, 76, 76) 0%, rgba(76, 76, 76, 0) 100%), radial-gradient(circle farthest-side at 0% 0%, rgb(58, 58, 58) 0%, rgba(58, 58, 58, 0) 100%), black",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#1a1a1a",
        "--theme-bg-hover": "#2a2a2a",
        "--theme-border": "#3a3a3a",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#cc7b19",
        "--button-color-hover": "#e59029",
        "--button-text": "#eeeeee",
        "--button-text-hover": "#ffffff",
        "--link-color": "#e5a00d",
        "--link-color-hover": "#ffffff",
        "--label-text-color": "#333333",
        "--modal-bg-color": "#282828",
        "--modal-header-color": "#323232",
        "--modal-footer-color": "#323232",
        "--drop-down-menu-bg": "#191a1c",
        "--accent-color": "229, 160, 13",
        "--accent-color-hover": "#ffc107",
        "--arr-queue-color": "#27c24c",
        "--plex-poster-unwatched": "#e5a00d",
      },
    },
    jellyfin: {
      name: "Jellyfin",
      variables: {
        "--theme-primary": "#aa5cc3",
        "--theme-primary-hover": "#9a4cb3",
        "--theme-accent": "#00a4dc",
        "--theme-bg": "#0b0b0f",
        "--theme-bg-dark": "#0b0b0f",
        "--theme-bg-card": "#1a1a24",
        "--theme-bg-hover": "#252535",
        "--theme-border": "#2a2a3a",
        "--theme-text": "#e5f6fb",
        "--theme-text-muted": "#8ca7b3",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#aa5cc3",
        "--button-color-hover": "#c77ddb",
        "--button-text": "#e5f6fb",
        "--button-text-hover": "#ffffff",
        "--link-color": "#aa5cc3",
        "--link-color-hover": "#c77ddb",
        "--label-text-color": "#ffffff",
        "--modal-bg-color": "#1a1a24",
        "--modal-header-color": "#0f0f18",
        "--modal-footer-color": "#0f0f18",
        "--drop-down-menu-bg": "#0b0b0f",
        "--accent-color": "170, 92, 195",
        "--accent-color-hover": "rgba(170, 92, 195, 0.8)",
        "--arr-queue-color": "#aa5cc3",
        "--plex-poster-unwatched": "#aa5cc3",
      },
    },
    emby: {
      name: "Emby",
      variables: {
        "--theme-primary": "#52b54b",
        "--theme-primary-hover": "#469d40",
        "--theme-accent": "#2c3e50",
        "--theme-bg": "#1c1c1c",
        "--theme-bg-dark": "#1c1c1c",
        "--theme-bg-card": "#252525",
        "--theme-bg-hover": "#2f2f2f",
        "--theme-border": "#3a3a3a",
        "--theme-text": "#ecf0f1",
        "--theme-text-muted": "#95a5a6",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#52b54b",
        "--button-color-hover": "#469d40",
        "--button-text": "#ecf0f1",
        "--button-text-hover": "#ffffff",
        "--link-color": "#52b54b",
        "--link-color-hover": "#6ac963",
        "--label-text-color": "#ffffff",
        "--modal-bg-color": "#252525",
        "--modal-header-color": "#1c1c1c",
        "--modal-footer-color": "#1c1c1c",
        "--drop-down-menu-bg": "#1c1c1c",
        "--accent-color": "82, 181, 75",
        "--accent-color-hover": "rgba(82, 181, 75, 0.8)",
        "--arr-queue-color": "#52b54b",
        "--plex-poster-unwatched": "#52b54b",
      },
    },
    Seerr: {
      name: "Seerr",
      variables: {
        "--theme-primary": "#6366f1",
        "--theme-primary-hover": "#4f46e5",
        "--theme-accent": "#a78bfa",
        "--theme-bg": "hsl(221, 39%, 11%)",
        "--theme-bg-dark": "hsl(215, 28%, 17%)",
        "--theme-bg-card": "#1f2937",
        "--theme-bg-hover": "#374151",
        "--theme-border": "#374151",
        "--theme-text": "#d1d5db",
        "--theme-text-muted": "#9ca3af",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#4f46e5",
        "--button-color-hover": "#6366f1",
        "--button-text": "#e5e7eb",
        "--button-text-hover": "#ffffff",
        "--link-color": "#6366f1",
        "--link-color-hover": "#a78bfa",
        "--label-text-color": "#000000",
        "--modal-bg-color": "#1f2937",
        "--modal-header-color": "#1f2937",
        "--modal-footer-color": "#1f2937",
        "--drop-down-menu-bg": "#374151",
        "--accent-color": "167, 139, 250",
        "--accent-color-hover": "rgba(167, 139, 250, 0.8)",
        "--arr-queue-color": "#6366f1",
        "--plex-poster-unwatched": "#6366f1",
      },
    },
    mind: {
      name: "Mind Stone",
      variables: {
        "--theme-primary": "#e1d500",
        "--theme-primary-hover": "#c3b900",
        "--theme-accent": "#fff200",
        "--theme-bg": "#0d0400",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#1a1800",
        "--theme-bg-hover": "rgba(51, 49, 0, 0.5)",
        "--theme-border": "rgba(228, 216, 0, 0.3)",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#e1d500",
        "--button-color-hover": "#c3b900",
        "--button-text": "#000000",
        "--button-text-hover": "#000000",
        "--link-color": "#fff200",
        "--link-color-hover": "#fff200cc",
        "--label-text-color": "#000000",
        "--modal-bg-color": "#1a1800",
        "--modal-header-color": "#1a1800",
        "--modal-footer-color": "#1a1800",
        "--drop-down-menu-bg": "#1a1800",
        "--accent-color": "228, 216, 0",
        "--accent-color-hover": "rgba(228, 216, 0, 0.8)",
        "--arr-queue-color": "#e1d500",
        "--plex-poster-unwatched": "#e1d500",
      },
    },
    power: {
      name: "Power Stone",
      variables: {
        "--theme-primary": "#a6288c",
        "--theme-primary-hover": "#85096b",
        "--theme-accent": "#df15b3",
        "--theme-bg": "#0b0833",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#1a0028",
        "--theme-bg-hover": "rgba(35, 0, 57, 0.5)",
        "--theme-border": "rgba(166, 40, 140, 0.3)",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#85096b",
        "--button-color-hover": "#85096bcc",
        "--button-text": "#eeeeee",
        "--button-text-hover": "#ffffff",
        "--link-color": "#df15b3",
        "--link-color-hover": "#ff00c8",
        "--label-text-color": "#ffffff",
        "--modal-bg-color": "#1a0028",
        "--modal-header-color": "#1a0028",
        "--modal-footer-color": "#1a0028",
        "--drop-down-menu-bg": "#1a0028",
        "--accent-color": "166, 40, 140",
        "--accent-color-hover": "rgba(166, 40, 140, 0.8)",
        "--arr-queue-color": "#d816ae",
        "--plex-poster-unwatched": "#d816ae",
      },
    },
    reality: {
      name: "Reality Stone",
      variables: {
        "--theme-primary": "#e80c0b",
        "--theme-primary-hover": "#e80c0bcc",
        "--theme-accent": "#e80c0b",
        "--theme-bg": "#08000d",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#2a0000",
        "--theme-bg-hover": "rgba(102, 5, 5, 0.5)",
        "--theme-border": "rgba(232, 12, 11, 0.3)",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#e80c0b",
        "--button-color-hover": "#e80c0bcc",
        "--button-text": "#eeeeee",
        "--button-text-hover": "#ffffff",
        "--link-color": "#e80c0b",
        "--link-color-hover": "rgba(232, 12, 11, 0.8)",
        "--label-text-color": "#ffffff",
        "--modal-bg-color": "#2a0000",
        "--modal-header-color": "#2a0000",
        "--modal-footer-color": "#2a0000",
        "--drop-down-menu-bg": "#2a0000",
        "--accent-color": "232, 12, 11",
        "--accent-color-hover": "rgba(232, 12, 11, 0.8)",
        "--arr-queue-color": "#e80c0b",
        "--plex-poster-unwatched": "#e80c0b",
      },
    },
    soul: {
      name: "Soul Stone",
      variables: {
        "--theme-primary": "#ff9900",
        "--theme-primary-hover": "#ff99cc",
        "--theme-accent": "#ff9900",
        "--theme-bg": "#3c0015",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#2a1000",
        "--theme-bg-hover": "rgba(140, 64, 2, 0.5)",
        "--theme-border": "rgba(255, 153, 0, 0.3)",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#ff9900",
        "--button-color-hover": "#ff99cc",
        "--button-text": "#eeeeee",
        "--button-text-hover": "#ffffff",
        "--link-color": "#ff9900",
        "--link-color-hover": "rgba(255, 153, 0, 0.8)",
        "--label-text-color": "#ffffff",
        "--modal-bg-color": "#2a1000",
        "--modal-header-color": "#2a1000",
        "--modal-footer-color": "#2a1000",
        "--drop-down-menu-bg": "#2a1000",
        "--accent-color": "255, 153, 0",
        "--accent-color-hover": "rgba(255, 153, 0, 0.8)",
        "--arr-queue-color": "#ff9900",
        "--plex-poster-unwatched": "#880030",
      },
    },
    space: {
      name: "Space Stone",
      variables: {
        "--theme-primary": "#0062ff",
        "--theme-primary-hover": "#0062ffcc",
        "--theme-accent": "#3d7eff",
        "--theme-bg": "#020013",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#001a3d",
        "--theme-bg-hover": "rgba(0, 57, 148, 0.5)",
        "--theme-border": "rgba(0, 98, 255, 0.3)",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#0062ff",
        "--button-color-hover": "#0062ffcc",
        "--button-text": "#eeeeee",
        "--button-text-hover": "#ffffff",
        "--link-color": "#3d7eff",
        "--link-color-hover": "#0062ff",
        "--label-text-color": "#ffffff",
        "--modal-bg-color": "#001a3d",
        "--modal-header-color": "#001a3d",
        "--modal-footer-color": "#001a3d",
        "--drop-down-menu-bg": "#001a3d",
        "--accent-color": "0, 98, 255",
        "--accent-color-hover": "rgba(0, 98, 255, 0.8)",
        "--arr-queue-color": "#0062ffcc",
        "--plex-poster-unwatched": "#0062ff",
      },
    },
    time: {
      name: "Time Stone",
      variables: {
        "--theme-primary": "#6df751",
        "--theme-primary-hover": "#04a800",
        "--theme-accent": "#6df751",
        "--theme-bg": "#00130c",
        "--theme-bg-dark": "#000000",
        "--theme-bg-card": "#001a00",
        "--theme-bg-hover": "rgba(2, 77, 0, 0.5)",
        "--theme-border": "rgba(109, 247, 81, 0.3)",
        "--theme-text": "#dddddd",
        "--theme-text-muted": "#999999",
        "--theme-text-hover": "#ffffff",
        "--button-color": "#04a800",
        "--button-color-hover": "rgba(4, 168, 0, 0.8)",
        "--button-text": "#000000",
        "--button-text-hover": "#000000",
        "--link-color": "#6df751",
        "--link-color-hover": "rgba(109, 247, 81, 0.8)",
        "--label-text-color": "#000000",
        "--modal-bg-color": "#001a00",
        "--modal-header-color": "#001a00",
        "--modal-footer-color": "#001a00",
        "--drop-down-menu-bg": "#001a00",
        "--accent-color": "109, 247, 81",
        "--accent-color-hover": "rgba(109, 247, 81, 0.8)",
        "--arr-queue-color": "#6df751cc",
        "--plex-poster-unwatched": "#6df751",
      },
    },
  };

  useEffect(() => {
    localStorage.setItem("posterizarr-theme", theme);
    document.documentElement.setAttribute("data-theme", theme);

    // Apply CSS variables for the selected theme
    const themeVars = themes[theme]?.variables;
    if (themeVars) {
      Object.entries(themeVars).forEach(([key, value]) => {
        document.documentElement.style.setProperty(key, value);
      });
    }
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, setTheme, themes }}>
      {children}
    </ThemeContext.Provider>
  );
};
